=== andrefonsecacc/-Structured_document_processing/Trabalho1_PDE/guiao.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/guiao"
	xmlns:tns="http://www.example.org/guiao" elementFormDefault="qualified">

	<element name="guiao" type="tns:guiao" />

	<complexType name="guiao">
		<sequence>
			<element name="cabeçalho" type="tns:cabeçalho" maxOccurs="1"
				minOccurs="1"></element>
			<element name="cenas" type="tns:cenas" maxOccurs="1"
				minOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="cabeçalho">
		<sequence>
			<element name="titulo" type="string" maxOccurs="1" minOccurs="1"></element>
			<!-- Nao faz logica ter um numero ilimitado de autores portanto limitei 
				pra 8 -->
			<element name="autor" type="string" minOccurs="1" maxOccurs="8"></element>
			<element name="dataPublicaçao" type="tns:dataPublicaçao"
				minOccurs="1" maxOccurs="1"></element>
			<element name="sinopse" type="string" minOccurs="0"
				maxOccurs="1"></element>
			<element name="Personagens" type="tns:Personagens" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="dataPublicaçao">
		<sequence>
			<element name="dia" type="string" minOccurs="1" maxOccurs="1"></element>
			<element name="mes" type="string" minOccurs="1" maxOccurs="1"></element>
			<element name="ano" type="string" minOccurs="1" maxOccurs="1"></element>
		</sequence>
	</complexType>


	<complexType name="Personagens">
		<sequence>
			<element name="nome" type="string" minOccurs="1" maxOccurs="1"></element>
			<element name="descriçao" type="string" minOccurs="1"
				maxOccurs="1"></element>
		</sequence>
		<attribute use="required" name="ID" type="ID" >			
		</attribute>
	</complexType>


	<complexType name="cenas">
		<!-- maxOccurs="unbounded" -->
		<!-- meter como opcional ??? -->
		<sequence>
			<choice>
				<element name="Temporada" type="tns:Temporada" minOccurs="0"
					maxOccurs="unbounded"></element>
				<element name="episodios" type="tns:episodios" minOccurs="0"
					maxOccurs="unbounded" ></element>
				<element name="Partes" type="tns:Partes" minOccurs="0"
					maxOccurs="unbounded"></element>
				<element name="Cena" type="tns:Cena" minOccurs="0"
					maxOccurs="unbounded">
				</element>
			</choice>
			<element name="Personagens" type="tns:Personagens" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="Temporada">
		<sequence>
			<element name="titulo" type="string" minOccurs="1" maxOccurs="1"></element>
			<element name="Personagens" type="tns:Personagens" minOccurs="0"
				maxOccurs="unbounded"></element>
			<element name="episodios" type="tns:episodios" minOccurs="1"
				maxOccurs="unbounded"></element>
			<element name="sinopse" type="string" minOccurs="0"
				maxOccurs="1"></element>
		</sequence>
		<attribute use="required" name="ID_Temporada" type="ID" />
	</complexType>

	<complexType name="episodios">
		<sequence>
			<element name="titulo" type="string" minOccurs="1" maxOccurs="1"></element>
			<element name="sinopse" type="string" minOccurs="0"
				maxOccurs="1"></element>
			<element name="Personagens" type="tns:Personagens" minOccurs="0"
				maxOccurs="unbounded"></element>
			<element name="Cena" type="tns:Cena" minOccurs="1" maxOccurs="unbounded"></element>
		</sequence>
		<attribute use="required" name="ID_Episodio" type="ID" />
	</complexType>


	<complexType name="Partes">
		<sequence>
			<element name="titulo" type="string" minOccurs="1" maxOccurs="1"></element>
			<element name="sinopse" type="string" minOccurs="0"
				maxOccurs="1"></element>
			<element name="Personagens" type="tns:Personagens" minOccurs="0"
				maxOccurs="unbounded"></element>
			<element name="Cena" type="tns:Cena" minOccurs="1" maxOccurs="unbounded"></element>
		</sequence>
		<attribute use="required" name="ID_Partes" type="ID" />
	</complexType>

	<complexType name="Cena" mixed="true">
		<sequence>
			<element name="texto" type="string" minOccurs="0"
				maxOccurs="unbounded"></element>
			<element name="fala" type="tns:fala" minOccurs="0"
				maxOccurs="unbounded"></element>
			<element name="refere" type="tns:refere" minOccurs="0"
				maxOccurs="unbounded"></element>
			<element name="contexto" type="string" minOccurs="0"
				maxOccurs="unbounded"></element>
			<element name="adereço" type="string" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
			 <attribute  use="required" name="contexto" type="string"></attribute>
	</complexType>

	<complexType name="fala" mixed="true">
	<sequence>
	<element name="texto" type="string"></element>
	<element name="comentario" type="string" minOccurs="0"
				maxOccurs="unbounded"></element>
	</sequence>
	<attribute use="required" name="ID" type="IDREF"></attribute>
	</complexType>
	
	<complexType name="refere">
	<sequence>
		<element name="texto" type="string"></element>
	</sequence>
	<attribute use="required" name="ID" type="IDREF"></attribute>
	</complexType>
	

</schema>

=== andrefonsecacc/-Structured_document_processing/Trabalho1_PDE/xsd_guiao.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:guiao xmlns:tns="http://www.example.org/guiao" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/guiao guiao.xsd ">
  <tns:cabeçalho>
    <tns:titulo>tns:titulo</tns:titulo>
    <tns:autor>tns:autor</tns:autor>
    <tns:autor>tns:autor</tns:autor>
    <tns:dataPublicaçao>
      <tns:dia>tns:dia</tns:dia>
      <tns:mes>tns:mes</tns:mes>
      <tns:ano>tns:ano</tns:ano>
    </tns:dataPublicaçao>
    <tns:Personagens ID="idvalue0">
    	<tns:nome>tns:nome</tns:nome>
    	<tns:descriçao>tns:descriçao</tns:descriçao>
    </tns:Personagens>
  </tns:cabeçalho>
  <tns:cenas>
  	<tns:Temporada ID_Temporada="idvalue01">
  		<tns:titulo>tns:titulo</tns:titulo>
  		<tns:episodios ID_Episodio="idvalue1">
  			<tns:titulo>tns:titulo</tns:titulo>
  			<tns:Cena contexto="">
  				<tns:fala ID="idvalue0">
  					<tns:texto>tns:texto</tns:texto>
  				</tns:fala>
  				<tns:refere ID="idvalue0">
  					<tns:texto>tns:texto</tns:texto>
  				</tns:refere>
  				<tns:adereço>tns:adereço</tns:adereço>
  				<tns:adereço>tns:adereço</tns:adereço></tns:Cena>
  		</tns:episodios>
  	</tns:Temporada></tns:cenas>
</tns:guiao>
