=== andrefonsecacc/-Structured_document_processing/Trabalho3_PDE/guiao.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY % PCD "(#PCDATA)">

<!ELEMENT guiao (cabeçalho,cenas)>
<!ELEMENT cabeçalho (personagens?,titulo,autor+,dataPublicaçao,sinopse?)>
<!ELEMENT dataPublicaçao (dia,mes,ano)>
<!ELEMENT titulo %PCD;>
<!ELEMENT autor %PCD;>
<!ELEMENT dia %PCD;>
<!ELEMENT mes %PCD;>
<!ELEMENT ano %PCD;>
<!ELEMENT sinopse %PCD;>

<!ELEMENT personagens (personagem)+>
<!ELEMENT personagem (nome,descriçao)>

<!ATTLIST personagem
	Personagem ID #REQUIRED >
	
<!ELEMENT nome %PCD;>
<!ELEMENT descriçao %PCD;>

<!ELEMENT cenas (personagens?,( temporada* | episodio* | partes* |cena*))>

<!ELEMENT temporada (episodio+,titulo,(personagens)?,(sinopse)?)>
<!ATTLIST temporada
	id ID #REQUIRED>

<!ELEMENT episodio (titulo,(personagens)?,(sinopse)?,cena+)>
<!ATTLIST episodio
	id ID #REQUIRED>
	
<!ELEMENT partes (titulo,(personagens)?,(sinopse)?,cena+)>
<!ATTLIST partes
	id ID #REQUIRED>
	
<!ELEMENT cena (#PCDATA | fala | refere |comentario |adereço )*>
<!ATTLIST cena
	contexto CDATA #IMPLIED>
	
<!ELEMENT fala (#PCDATA | comentario)*>
<!ATTLIST fala
	Personagem IDREF #REQUIRED
	>

<!ELEMENT comentario %PCD;>
<!ELEMENT refere %PCD;>
<!ATTLIST refere
	Personagem IDREF #REQUIRED>
<!ELEMENT adereço %PCD;>

=== andrefonsecacc/-Structured_document_processing/Trabalho1_PDE/dtd_guiao.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guiao SYSTEM "guiao.dtd" >
<guiao>
	<cabeçalho>
		<personagens>
			<personagem Personagem="idvalue0">
				<nome>Melkor</nome>
				<descriçao>The first Dark Lord</descriçao>
			</personagem>
			<personagem Personagem="idvalue1">
				<nome>Celebrimbor</nome>
				<descriçao> Ñoldorin prince</descriçao>
			</personagem>
			<personagem Personagem="idvalue2">
				<nome>Fëanor</nome>
				<descriçao> the Ñoldor king</descriçao>
			</personagem>
		</personagens>
		<titulo>Trabalho nº1 da cadeira Processamento de documentos
			estruturados</titulo>
		<autor>
			André Fonseca</autor>
		<autor>J. R. R. Tolkien</autor>
		<dataPublicaçao>
			<dia>03</dia>
			<mes>11</mes>
			<ano>2016</ano>
		</dataPublicaçao>
	</cabeçalho>
	<cenas>
		<partes id="idvalue14">
			<titulo>The Quest of the Silmaril</titulo>
			<personagens>
				<personagem Personagem="idvalue3">
					<nome> Beren</nome>
					<descriçao>Human</descriçao>
				</personagem>
			</personagens>
			<cena contexto="first age of middle earth">
				
				<fala Personagem="idvalue0">i am seeking to recover a Silmaril,<comentario>comentario</comentario></fala>
				<fala Personagem="idvalue0"></fala>
				<refere Personagem="idvalue0">refere</refere></cena>
			<cena contexto="first age of middle earth">
				<refere Personagem="idvalue0">refere</refere>
				<fala Personagem="idvalue0">
					<comentario>comentario</comentario></fala>
				<adereço>adereço</adereço>
				<fala Personagem="idvalue0"></fala>
				<refere Personagem="idvalue0">refere</refere>
				<adereço>adereço</adereço></cena>
		</partes></cenas>
</guiao>

=== andrefonsecacc/-Structured_document_processing/Trabalho3_PDE/dtd_guiao2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guiao SYSTEM "guiao.dtd" >
<guiao>
	<cabeçalho>
		<personagens>
			<personagem Personagem="Donna">
				<nome>Donna</nome>
				<descriçao>Secretaria</descriçao>
			</personagem>
		</personagens>
		<titulo>Suits</titulo>
		<autor>André Fonseca</autor>
		<dataPublicaçao>
			<dia>27</dia>
			<mes>11</mes>
			<ano>2016</ano>
		</dataPublicaçao>
		<sinopse>Serie televisiva sobre advogados </sinopse>
	</cabeçalho>
	<cenas>
		<temporada id="idvalue0">
			<episodio id="idvalue1">
				<titulo>O inicio de tudo</titulo>
				<personagens>
					<personagem Personagem="Mike">
						<nome>Mike</nome>
						<descriçao>falso advogado com memoria fotografica</descriçao>
					</personagem>
				</personagens>
				<cena contexto="Sala de conferencias do Hilton Hotel">
					<adereço>mala cheia de droga</adereço>
					<adereço>garrafa de whisky</adereço>
					<fala Personagem="Harvey">Estou a precisar de um novo advogado
						associado
					</fala>
					<fala Personagem="Mike">
						Que tal eu Harvey ?!

						<comentario>enquanto diz isto pega na mala</comentario>
					</fala>
				</cena>
			</episodio>
			<episodio id="idvalue2">
				<titulo>Hotel Hilton</titulo>
				<cena contexto="Sala de conferencias">
					<fala Personagem="Mike">Achas que me consigo safar disto?</fala>
					<adereço>Mala cheia de drogas</adereço>
				</cena>
			</episodio>
			<titulo>Temporada1</titulo>
		</temporada>
		<temporada id="idvalue23">
			<episodio id="idvalue12131">
				<titulo>Episodio Piloto </titulo>
				<personagens>
					<personagem Personagem="Harvey">
						<nome>Harvey</nome>
						<descriçao>descriçao</descriçao>
					</personagem>
				</personagens>
				<cena contexto="Firma de advogados">
					<fala Personagem="Donna">Assim começa o dia, altura de fazer uma
						caneca de café pro big boss
					</fala>
				</cena>
				<cena contexto="Escritorio da firma">
					<fala Personagem="Harvey">
						Onde esta o meu café?!!!!
						<comentario>enquanto boceja</comentario>
					</fala>
				</cena>
			</episodio>
			<titulo>Temporada 2</titulo>
		</temporada>
		</cenas>
		</guiao>

=== andrefonsecacc/-Structured_document_processing/Trabalho2_PDE/dtd_guiao.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guiao SYSTEM "guiao.dtd" >
<guiao>
	<cabeçalho>
		<personagens>
			<personagem Personagem="Eru">
				<nome>Eru</nome>
				<descriçao>The One </descriçao>
			</personagem>
			<personagem Personagem="Eldar">
				<nome>Eldar</nome>
				<descriçao>The Maiar</descriçao>
			</personagem>
			<personagem Personagem="Manwë">
				<nome>Manwë</nome>
				<descriçao> the Ñoldor king</descriçao>
			</personagem>
			<personagem Personagem="Narrador">
				<nome>Narrador</nome>
				<descriçao>pessoa que esta a ler</descriçao>
			</personagem>
		</personagens>
		<titulo>Trabalho nº2 - Guiao do Silmarillion</titulo>
		<autor>André Fonseca</autor>
		<autor>J. R. R. Tolkien</autor>
		<dataPublicaçao>
			<dia>03</dia>
			<mes>11</mes>
			<ano>2016</ano>
		</dataPublicaçao>
	</cabeçalho>
	<cenas>
		<partes id="idvalue1">
			<titulo>The History of the Silmarils</titulo>
			<personagens>
				<personagem Personagem="Melkor">
					<nome>Melkor</nome>
					<descriçao>The DarkLord</descriçao>
				</personagem>
				<personagem Personagem="Yavanna">
					<nome>Yavanna</nome>
					<descriçao>Elf Lord</descriçao>
				</personagem>
			</personagens>
			<cena contexto="the Beginning of Days">

				<fala Personagem="Narrador">It is told among the wise that the First War
					began
					before Arda was full-shaped, and ere yet there was any
					thing
					that grew or walked upon earth; and for long Melkor
					had the upper
					hand. But in the midst of the war a spirit of
					great strength and
					hardihood came to the aid of the Valar,
					hearing in the far heaven
					that there was battle in the Little Kingdom; and
					Arda was filled
					with the sound of his
					laughter. So came Tulkas the Strong, whose
					anger passes
					like a mighty wind, scattering cloud and darkness
					before it;
					and Melkor fled before his wrath and his laughter, and
					forsook Arda, and there was peace for a long age. And
					Tulkas
					remained and became one of the Valar of the Kingdom of Arda; but
					Melkor brooded in the outer
					darkness, and his hate was given to
					Tulkas for ever after.
				</fala>
				<fala Personagem="Melkor">Thus ended the Spring of Arda. The dwelling of
					the Valar uponAlmaren was utterly destroyed!!!
				</fala>
			</cena>

			<cena contexto="the Coming of the Elves and the
Captivity of Melkor">
				<fala Personagem="Narrador">
					t in the north
					Melkor
					built his strength, and he
					slept
					not, but watched, and laboured; and the evil things that he
					had perverted walked abroad, and the dark and slumbering woods were
					haunted by monsters and shapes of dread. And in Utumno he gathered
					his demons about him, those
					spirits who first adhered to him in the
					days of his splendour,
					and became most like him in his corruption
				</fala>
				<adereço>Sword of flames</adereço>
				<refere Personagem="Melkor">Melkor</refere>
			</cena>
		</partes>
		</cenas>
</guiao>
